/*
 * 	 digits_4x8.c
 *
 * Font generated by ATNEL - SFG (part of PixelFactory)
 * http://atnel.pl/pixel-factory.html
 * (C) 2015 by Atnel. Miros³aw Kardaœ
 */
#include <avr/io.h>
#include <avr/pgmspace.h>

#include "mk_fonts.h"


//  Font data for digits_4x8


// Character bitmaps for digits_4x8
const uint8_t digits_4x8Bitmaps[] PROGMEM = {
	0xFF, 0x81, 0x81, 0xFF,                           // char 0  (48)
	0x04, 0x82, 0xFF, 0x80,                           // char 1  (49)
	0xF3, 0x91, 0x91, 0x9F,                           // char 2  (50)
	0x81, 0x89, 0x89, 0xFF,                           // char 3  (51)
	0x1F, 0x10, 0x10, 0xFF,                           // char 4  (52)
	0xCF, 0x89, 0x89, 0xF9,                           // char 5  (53)
	0xFF, 0x89, 0x89, 0xFB,                           // char 6  (54)
	0x03, 0x01, 0x01, 0xFF,                           // char 7  (55)
	0xFF, 0x89, 0x89, 0xFF,                           // char 8  (56)
	0xDF, 0x91, 0x91, 0xFF,                           // char 9  (57)
	0x24,                                          // char :  (58)
	0x42,                                          // char ;  (59)
};

// descriptors
const MHFONT_CHAR_INFO digits_4x8Descriptors[] PROGMEM = {
	{ 4,0 },	// char 0  (48)
	{ 4,4 },	// char 1  (49)
	{ 4,8 },	// char 2  (50)
	{ 4,12 },	// char 3  (51)
	{ 4,16 },	// char 4  (52)
	{ 4,20 },	// char 5  (53)
	{ 4,24 },	// char 6  (54)
	{ 4,28 },	// char 7  (55)
	{ 4,32 },	// char 8  (56)
	{ 4,36 },	// char 9  (57)
	{ 1,40 },	// char :  (58)
	{ 1,41 },	// char ;  (59)
	{ 0,0 },	//
};

// Font information
const MHFONT_INFO digits_4x8 PROGMEM = {
	0,	// Down Space in pixels
	8,	// Caracter height
	'0',	// Start character
	2,	// number of pixels of interspace between characters
	2,	// number of pixels of space character
	digits_4x8Descriptors,	// number of pixels of space character
	digits_4x8Bitmaps,	// number of pixels of space character
	0,	// (Pointer) Font filename saved on SD card or 0 (null) otherwise  )
	0,	// bits and byte orientation 0-T2B, 1-L2R
};
