/*
 * 	 DIGITS_5x8.c
 *
 * Font generated by ATNEL - SFG (part of PixelFactory)
 * http://atnel.pl/pixel-factory.html
 * (C) 2015 by Atnel. Miros³aw Kardaœ
 */
#include <avr/io.h>
#include <avr/pgmspace.h>

#include "mk_fonts.h"


//  Font data for DIGITS_5x8


// Character bitmaps for DIGITS_5x8
const uint8_t DIGITS_5x8Bitmaps[] PROGMEM = {
	0x60,                                          // char .  (46)
	0x20, 0x10, 0x08, 0x04, 0x02,                      // char /  (47)
	0x7E, 0x81, 0x81, 0xFF, 0x7E,                      // char 0  (48)
	0x00, 0x82, 0xFF, 0xFF, 0x80,                      // char 1  (49)
	0xE2, 0x91, 0x91, 0x9F, 0xCE,                      // char 2  (50)
	0x42, 0x89, 0x89, 0xFF, 0x76,                      // char 3  (51)
	0x3F, 0x20, 0x20, 0xFC, 0xFC,                      // char 4  (52)
	0x4F, 0x89, 0x89, 0xFB, 0x73,                      // char 5  (53)
	0x7E, 0x89, 0x89, 0xFB, 0x72,                      // char 6  (54)
	0x03, 0xF1, 0xF9, 0x0F, 0x07,                      // char 7  (55)
	0x76, 0x89, 0x89, 0xFF, 0x76,                      // char 8  (56)
	0x4E, 0x91, 0x91, 0xFF, 0x7E,                      // char 9  (57)
	0x66,                                          // char :  (58)
};

// descriptors
const MHFONT_CHAR_INFO DIGITS_5x8Descriptors[] PROGMEM = {
	{ 1,0 },	// char .  (46)
	{ 5,1 },	// char /  (47)
	{ 5,6 },	// char 0  (48)
	{ 5,11 },	// char 1  (49)
	{ 5,16 },	// char 2  (50)
	{ 5,21 },	// char 3  (51)
	{ 5,26 },	// char 4  (52)
	{ 5,31 },	// char 5  (53)
	{ 5,36 },	// char 6  (54)
	{ 5,41 },	// char 7  (55)
	{ 5,46 },	// char 8  (56)
	{ 5,51 },	// char 9  (57)
	{ 1,56 },	// char :  (58)
	{ 0,0 },	//
};

// Font information
const MHFONT_INFO DIGITS_5x8 PROGMEM = {
	0,	// Down Space in pixels
	8,	// Caracter height
	'.',	// Start character
	2,	// number of pixels of interspace between characters
	2,	// number of pixels of space character
	DIGITS_5x8Descriptors,	// number of pixels of space character
	DIGITS_5x8Bitmaps,	// number of pixels of space character
	0,	// (Pointer) Font filename saved on SD card or 0 (null) otherwise  )
	0,	// bits and byte orientation 0-T2B, 1-L2R
};
